### ISSUE TITLE
Crash at startup if iOS < 12.2

### ISSUE THREAD

**Issue by quentinR0bert** [roubachof/Xamarin.Forms.Nuke#7]
Hi,

I have add your library to my application and it's work like a charm, but only on > iOS 12.2.

My app crash a the startup if the device is < iOS 12.2 so it's seem related to Swift Support.

It's seem that maybe your have forgot to add the Swift Support on your binding.

I have added the Xamarin.iOS.SwiftRuntimeSupport and try with the Xamarin.Swift (of Flash 3001) on my projet but it didn't resolve the crash.

**Comment by roubachof** [comment]
hey man!

Do you have some doc that tells that you need to add the Swift Support package to my binding?
I don't really know how to do it

**Comment by quentinR0bert** [comment]
> In order to add support for iOS 12.1 and earlier, you want to ship specific Swift dylibs used to compile your framework. Use the Xamarin.iOS.SwiftRuntimeSupport NuGet package to process and copy required libs with your IPA. Add the NuGet reference to your target project and rebuild the application. No further steps are required, the NuGet package will install specific tasks, which are executed with the build process, identify required Swift dylibs and package them with the final IPA.

On the walkthrough of a binding : https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough

**Comment by roubachof** [comment]
So according to the docs, you just have to add a dependency on this nugget package to the shipped nuget. Have you tried fork the project and add this dll?

**Comment by taublast** [comment]
Hi i'm not sure if its same issue or another one, i'm crashing after splashscreen on simulator with ios 10.3 (so maybe it's the same issue), but as you will read "mach-o, but not built for iOS simulator", well the log follows:

Version:               1.001 (1001)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [12607]
Responsible:           SimulatorTrampoline [7469]
User ID:               501

Date/Time:             2020-07-12 18:11:13.944 +0300
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        551FA522-2E6B-7374-477D-8A171EB831F3

Sleep/Wake UUID:       7EA2B482-128B-409A-8FC4-23B9F6AC7025

Time Awake Since Boot: 31000 seconds
Time Since Wake:       13000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FALLBACK_LIBRARY_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_SHARED_REGION=avoid

Dyld Error Message:
  Library not loaded: @rpath/NukeProxy.framework/NukeProxy
  Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/D06114ED-6D9F-4C47-868A-AFBD51F54B09/data/Containers/Bundle/Application/C4EBE791-49F7-400E-8E4A-8869B14B9612/AppoMobi.iOS.app/AppoMobi.iOS
  Reason: no suitable image found.  Did find:
 /Users/airboom/Library/Developer/CoreSimulator/Devices/D06114ED-6D9F-4C47-868A-AFBD51F54B09/data/Containers/Bundle/Application/C4EBE791-49F7-400E-8E4A-8869B14B9612/AppoMobi.iOS.app/Frameworks/NukeProxy.framework/NukeProxy: mach-o, but not built for iOS simulator

**Comment by roubachof** [comment]
did you add swift runtime package to your app as described here: https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough ?

**Comment by taublast** [comment]
Nope just installed nuget..

**Comment by roubachof** [comment]
![image](https://user-images.githubusercontent.com/596903/87290903-e02cef80-c4fe-11ea-9bde-c180cbc18b88.png)

**Comment by taublast** [comment]
Thanks! Why don't we reference this swift nuget from the main nuke nuget to avoid confusion? Might be ok since ios has an awesome linker?.

**Comment by roubachof** [comment]
yup, should be a thing for version 9

**Comment by roubachof** [comment]
will be added in v8.4.1

**Comment by spidei** [comment]
I'm having problems adding SwiftRuntimeSuport on iOS<12.2 devices, even on v8.4.1, crashes after slash
I have to investigate more later today, but so far the errors are:
Error: "Exec" task received an invalid value for the "StdOutEncoding" parameter
Error: "Exec" task received an invalid value for the "StdErrEncoding" parameter
On Xamarin.iOS.SwiftRuntimeSupport.targets

I'm on Visual Studio for Windows with remote Mac connection, but I think will [not work on Windows](https://github.com/Flash3001/Xamarin.Swift/blob/master/SwiftSupport/ProduceIncludeFrameworksCommand.cs).

I have to try it harder with Visual Studio on Mac. @taublast do you have this error, or works for you?

**Comment by moustafashaban** [comment]
@roubachof is there any time that this will be available in nuget?
thanks

**Comment by roubachof** [comment]
it is now, but Xamarin.SwiftRuntime seems to cause issues on the apple store: https://github.com/roubachof/Xamarin.Forms.Nuke/issues/15

So if you want to add support to the package you will have to add yourself the SwiftRuntime nuget

**Comment by moustafashaban** [comment]
sorry I am confused, 
I have these scenarios
I added Nuke and uploaded a version my device closes directly (I can see only the splash) and my device has 12.4.8
I then added Xamarin.iOS.SwiftRuntime then the app is no more accepted from Apple (same as #15)

if I remove Nuke and SwiftRuntime everything works fine

**Comment by roubachof** [comment]
ok so you don't need SwiftRuntime  since you ios version is > 12.2.
It must be another bug with the lib.
Please check your simulator or device crash logs and open an issue.

**Comment by roubachof** [comment]
## Support for iOS < 12.2

As specified here: https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough#consume-the-binding-library

You need to add the [Xamarin.iOS.SwiftRuntimeSupport NuGet package](https://www.nuget.org/packages/Xamarin.iOS.SwiftRuntimeSupport/) to your target project if you want to support iOS 12.1 and earlier.
Please read the above doc to submit an app with such support.
